#!/usr/bin/env ruby
require 'json'

JSON.parse(%x[foo-focus-parent-json])["children"].each do |c|
  if c["type"] == "client" then
    puts %x[xptr-to-title #{c["id"]}]
  else 
    puts "#{c["layout"]} #{c["children"].count}"
  end
end
