Handlers:
  default    : surf

  # Non-URI Based handlers
  surf       : surf %s
  chromium   : chromium %s
  private    : chromium --incognito %s
  ff         : firefox %s

  # URI-Based Handlers
  https?     : surf %s
  xml        : newsreader %s

  sh         : urxvt -e %s  # Termial Handlers, launch new term
  s          : exec %s      # Single command run




# Either search engines URIs or terminal prefixes
# '%s' will be replaced with the buffer
Searches:
  default     : gg

  # Searches Queries
  ddg         : https://duckduckgo.com/?q=%s
  gg          : https://google.com/search?q=%s
  im          : https://google.com/search?tbm=isch&q=%s
  wiki        : https://en.wikipedia.org/w/index.php?search=%s
  wb          : https://secure.wikimedia.org/wikibooks/en/wiki?search=%s
  mdn         : https://developer.mozilla.org/en-US/search?q=%s
  aur         : https://aur.archlinux.org/packages.php?O=0&K=%s&do_Search=Go
  aw          : https://wiki.archlinux.org/index.php?search=%s
  so          : http://stackoverflow.com/search?q=%s
  gh          : http://github.com/search?q=%s
  wa          : http://wolframalpha.com/input?i=%s
  discogs     : http://discogs.com/search?q=%s
  rym         : http://rateyourmusic.com/search?searchtype=a&searchterm=%s
  sep         : http://plato.stanford.edu/search/searcher.py?query=%s
  ud          : http://urbandictionary.com/define.php?term=%s
  ebay        : http://search.ebay.com/search/search.dll?query=%s
  stock       : https://www.google.com/finance?q=%s
  define      : http://www.merriam-webster.com/dictionary/%s
  syn         : http://www.collinsdictionary.com/dictionary/english-thesaurus/%s
  weather     : http://asciiw.com/%s

  yt          : urxvt -e youtube-viewer %s
  j           : urxvt -e z %s & ranger
  man         : urxvt -e man %s
  cd          : urxvt -e ranger %s

  kill        : killall %s
  workspace   : workspace %s




Shorthands:
  config      : sh vim /home/mil/.lunchcfg.yaml
  site5       : sh ssh miles@userbound.com
  dreamhost   : sh ssh bladdo@bladdo.net
  x300        : sh ssh mil@x300
  x40         : sh ssh mil@x40

  # Filebrowser
  ranger      : sh ranger
  brows       : http://localhost:3400


  # Window Manager
  down        : sh i3 focus down
  up          : sh i3 focus up
  left        : sh i3 focus left
  right       : sh i3 focus right

  # Tmux Sessions
  notes       : sh tmx notes
  music       : sh dtach -A /home/mil/IPC/Sockets/music fish -c dvtm
  torrent     : sh dtach -A /home/mil/IPC/Sockets/torrent fish -c dvtm
  irc         : sh dtach -A /home/mil/IPC/Sockets/irc fish -c dvtm
  chat        : sh dtach -A /home/mil/IPC/Sockets/chat fish -c pidgin
  network     : sh tmx network
  system      : sh tmx system

  # Alarm Clock
  wakeup      : sh wakeup
  crontab     : sh crontab -e
  cron        : sh crontab -e

  # Audio
  wuvt        : sh urxvt -fn "xft:Envy Code R-30" -e sleepit 10 wuvt
  bt          : sh urxvt -fn "xft:Envy Code R-30" -e sleepit 10 bt
  mixer       : sh alsamixer
  eq          : sh alsamixer -D equal
  dj          : sh mpctrl

  pause       : s mediaControl pause
  next        : s mediaControl next
  previous    : s mediaControl previous
  mute        : s amixer set Master 0% mute

  # Locations
  campus      : sh campus
  home        : sh home

  # System
  monitor      : s arandr
  remap        : s xmodmap ~/.xmodmap
  viewsonic    : s viewsonic
  dualscreen   : s dualscreen
  singlescreen : s singlescreen
  morning      : s light on
  goodnight    : s xset dpms force suspend && light off
  lock         : s slock
  invert       : s xcalib -a -invert
  suspend      : s sudo pm-suspend
  shutdown     : s sudo /usr/bin/systemctl hibernate
  reboot       : s sudo /usr/bin/systemctl reboot
  halt         : s sudo /usr/bin/systemctl poweroff
  fans         : s fans

  # Games
  clock       : s urxvt -fn "xft:Envy Code R-20" -e tty-clock -c -s -C 2
  tetris      : sh vitetris
  word        : s abiword

  # Tools
  code        : s ranger /home/mil/Code
  edit        : s surf 'http://userbound.com/ui/mil-edit'
  email       : s urxvt -e mutt
  webmail     : s chromium --incognito http://userbound.com/webmail
  download    : s launch '`sselp`'
  auth        : s 'vt_auth'
  netgood     : s ping google.com
  root        : s sudo su
  cron        : s crontab -e
  top         : s htop

  # Bookmarks
  bookmarks   : sh ranger /home/mil/Code/Bitbucket/bookmarks
  otw         : http://onethingwell.org
  hn          : http://news.ycombinator.com
  bb          : http://bitbucket.org
  scholar     : http://scholar.vt.edu

  # Graphics
  calibrate   : sh dispwin
  gimp        : s gimp
  phatch      : s phatch
  picker      : s gcolor2
  ruler       : s xmeasure | tr -d '\n' | xargs -I INF zenity --info --text='INF'
  screenshot  : s scrot
  c           : s xdotool key c l o n e Return

  # Skanote
  skanote-dev : sh chromium --app=http://localhost:9292
  skanote     : sh chromium --app=http://morning-plains-8512.herokuapp.com
