#!/usr/bin/env bash

# Restow all configs
stow -t ~ $(ls -d */) --ignore gentoo
sudo ln -s $(readlink -f gentoo/savedconfig) /etc/portage/savedconfig
sudo ln -s $(readlink -f gentoo/patches) /etc/portage/patches
