#!/usr/bin/env bash

# Restow all configs
stow -t ~ $(ls -d */) --ignore gentoo
#sudo ln -sfn $(readlink -f gentoo/savedconfig) /etc/portage/
#sudo ln -sfn $(readlink -f gentoo/patches) /etc/portage/
