#!/usr/bin/env ruby
ENV['DISPLAY'] = ':0'
%x[xset dpms force on]

Thread.new do
  %x[i3lock -i /home/mil/.alarm.png]
  %x[xcalib -a -clear]
  exit
end

Thread.new do
  loop do
    %x[mplayer ~/.alarm.mp3]
  end
end

loop do
  %x[xcalib -a -invert]
  sleep 0.1
end
