#!/bin/bash
# Shares internet from wlan0 through eth0
case "$1" in 
    start)
ifconfig eth0 up
ifconfig eth0 192.168.0.1
iptables --table nat --append POSTROUTING --out-interface wlan0 -j MASQUERADE
iptables --append FORWARD --in-interface eth0 -j ACCEPT
echo 1 > /proc/sys/net/ipv4/ip_forward
echo "set other computers in the range of"
echo "192.168.0.0 255.255.255.0"
echo "gateway 192.168.0.1"
echo "dns 192.168.0.1"   % this is actually my router, use yours, or another dns service.
;;
    stop)
echo 0 > /proc/sys/net/ipv4/ip_forward
ifconfig eth0 down
iptables --table nat --delete POSTROUTING --out-interface wlan0 -j MASQUERADE
;;
    *)
echo "usage: $0 {start|stop}"
;;
esac
