#!/usr/bin/env sh

tflt() {
  TIME=$(eval date -d \""$@"\" +%s)
  cat | awk "\$1 > $TIME"
}


D="/tmp/sfeed_$(echo $@ | sed 's/ /_/g')"
mkdir -p $D
rm -rf $D/*

cd ~/.sfeed/feeds/
for f in $(ls)
do
  cat $f | tflt $@ > $D/$f
  [ -s $D/$f ] || rm $D/$f
done
echo $D
