#!/usr/bin/env sh
ID=999

ispp() {
    grep -qi pinephone /etc/deviceinfo
}

control() {
    amixer scontrols | grep -Eo "'[^']+'" | tr -d "'" | grep -Ei 'Master|Speaker|Headphone|PCM' | head -n 1
}

get_volume() {
    amixer -M get "$(control)" | awk 'END { print $0, value }' | awk '{print $4}' | grep -Eo '[0-9]+'
}

is_mute() {
    amixer get "$(control)" | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

send_notification() {
    volume=`get_volume`
    dunstify -r $ID  -u normal "${volume}%"
}

up() {
    amixer set "$(control)" on > /dev/null
    amixer set "$(control)" 1+ > /dev/null
    send_notification
}

down() {
    amixer set "$(control)" on > /dev/null
    amixer set "$(control)" 1- > /dev/null
    send_notification
}

mute() {
    amixer set "$(control)" toggle > /dev/null
    if is_mute ; then
      dunstify -r $ID -u normal "Mute"
    else
      send_notification
    fi
}

"$@"
