#!/bin/bash
cd /tmp

# Xcwd
git clone https://github.com/schischi/xcwd
cd xcwd
make
sudo make install

# NVM
curl -o https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash

# RVM
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
curl -sSL https://get.rvm.io | bash -s stable

# Mils Lunch
nvm install v5.0.0
nvm use v5.0.0
npm install -g mils-lunch

# Envy Code R
wget http://download.damieng.com/fonts/original/EnvyCodeR-PR7.zip
unzip EnvyCodeR-PR7.zip
rsync -r EnvyCodeR-PR7/*.ttf ~/.fonts/
