#!/usr/bin/env ruby
require 'json'

def battery
  buff = %x[battery].chomp!.split(' ')
  " " + buff[1] + " "
end
def temp
  n = File.read("/sys/class/thermal/thermal_zone0/temp").chomp!.to_i / 1000
  #return "" + 
  return " " + n.to_s + "°C "
end

def network
  l = %x[netctl list].split("\n").select { 
    |n| n if n[0] == "*"
  }
  l.first.gsub!("* ", "")
  " " + l.first + " "
end


def information
  [
  #  {
  #    "name" => "time",
  #    "full_text" => %x[date].chomp!,
  #    "color" => "#171717" 
  #  },
  #
  #
    {
      "name" => "temp",
      "full_text" => temp,
      "color" => "#171717"
    },
    {
      "name" => "network",
      "full_text" => network,
      "color" => "#171717"
    },
    {
      "name" => "battery",
      "full_text" => battery,
      "color" => "#171717"
    }









  #  {
  #    "name" => "bus",
  #    "full_text" => %x[bt 2> /tmp/err].chomp!,
  #    "separator" => true,
  #    "color" => "#171717" 
  #  }
  ].to_json
end

puts '{ "version": 1 }'
puts "["
puts "[]"


loop do
  puts "," + information
  STDOUT.flush
  sleep 40
end
