#!/usr/bin/env ruby
davUrl = "https://scholar.vt.edu/dav"
classes = {
  "PHIL-2125" => "2b31e19b-30dc-41f8-b513-ae282d724165",
  "PSYC-4214" => "f86b9a83-b7f3-40b0-9c2d-8ae82bf41dc7",
  "PHIL-4224" => "97530412-e0ec-4971-978c-90f99a0eecac",
  "PHIL-3454" => "69ae8a10-31af-44c2-b4bc-6b3374d9fede",
  "PSYC-3014" => "22556b4a-6af1-4933-b544-fd5801890474"
}

if (classes[ARGV[0]]) then
  puts "\e[33m#{ARGV[0]}\e[0m ==> \e[32mcadaver #{classes[ARGV[0]]}\e[0m"
  exec "cadaver #{davUrl}/#{classes[ARGV[0]]}"

else
  puts "Invalid Class Options are:"
  classes.each { |a, b|
    puts "[\e[32m#{a}\e[0m] "
  }
  print "\n"
end

