#!/usr/bin/ruby
xinit = "/home/mil/.xinitrc"
commands = {
  "foowm" => [
    "if [ -f \"/usr/bin/tpb\" ];\nthen\nsudo tpb &\nfi",
    "bar-start", "xbindkeys", "dunst", "keynav",
    "exec foo-wm"
],
  "dev" => [
    "bar-start",
    "xbindkeys -f /home/mil/Code/Github/foo-wm/config/.xbindkeysrc",
    "exec /home/mil/Code/Github/foo-wm/foo-wm"
],
  "no-wm" => [
    "bar-start",
    "xbindkeys",
    "x-focus-manager",
    "x-session"
],
  "euclid" => [
    "euclid-wm"
],

  "meis-wm" => [
    "bar-start",
    "sxhkdrc -c /home/mil/.config/sxhkd/sxhkdrc",
    "exec /home/mil/Code/Github/meis-wm/meis-wm",
    "exec /home/mil/Code/Github/meis-wm/x-session"
],

  "column" => [
    "xbindkeys -f /home/mil/Code/Github/column-wm/.xbindkeysrc",
    "exec /home/mil/Code/Github/column-wm/column-wm",
    "exec /home/mil/Code/Github/column-wm/x-session"
],



  "scrollwm" => [
    "bar-start",
    "xbindkeys",
    "exec scrollwm"
],

  "bspwm" => [
    "bar-start",
    "xbindkeys  -f /home/mil/.bp",
    "exec bspwm"
],
  "wmii" => [
    "xbindkeys",
    "exec wmii",
    "urxvt"
],


  "hack" => [
    "bar-start",
    "xcalib -a -invert",
    "xbindkeys -f /home/mil/Code/Github/foo-wm/config/.xbindkeysrc",
    "exec /home/mil/Code/Github/foo-wm/foo-wm"
],

  "simplewm" => [
    "xbindkeys",
    "exec /home/mil/code/repos/github/simple-wm/simple-wm"
],
  "i3" => [
    "keynav",
    #"xchainkeys",
   # "xbindkeys -f /home/mil/.i3/.xbindkeysrc",
    "dunst",
    "exec i3"
],
  "sawfish" => [
    "xbindkeys",
    "exec sawfish"
],

  "herbs" => [
    #		"xchainkeys",
    "dunst",
    "exec herbstluftwm"
],
  "ttwm" => [
    "xchainkeys",
    "xbindkeys",
    "dunst",
    "dropboxd",
    "exec /home/mil/code/contrib/ttwm/ttwm"
],
  "jwm" => [
    "xbindkeys",
    "exec jwm"
],
  "monsterwm" => [
    #"xbindkeys",
    "exec monsterwm"
],
  "local-dwm" => [
    "xbindkeys",
    "exec /home/mil/code/scratch/c/dwm-6.0/dwm"
],

  "dwm" => [ 
    "xbindkeys -f /home/mil/.config/dwm/.xbindkeysrc", 
    "exec dwm" 
  ],
  "windowlab" => [
    "xbindkeys",
    "exec windowlab"
]
}
if (commands[ARGV[0]]) then
  finalOut = ""

  File.open(xinit, "r").each_line do |line|
    finalOut += line
    if (line =~ /setwm/) then
      break
    end
  end

  commands[ARGV[0]].each do |command|
    finalOut += command
    unless (commands[ARGV[0]].last == command) then
      finalOut += ' &'
    end
    finalOut += "\n"
  end

  File.delete(xinit)
  File.open(xinit, "w") do |file| 
    file.write(finalOut)
  end
  puts "[\e[32m#{ARGV[0]}\e[0m] ===> [\e[35m#{xinit}\e[0m]"
else
  puts "No WM specified in setwm script"
end
