#!/usr/bin/ruby
require 'uri'

url ="#{ARGV[0]}"
if (!(url =~ /^http(s)?:\/\//)) then
	url = "https://#{url}"
end

if (!(url =~ /^.+\..+/)) then
	print 0
	exit
end

begin
	URI.parse(url);
	print 1 
rescue
	print 0 
end
