#!/bin/bash
# Input Handler:
# 1. Given file --> opens using specified handler in extensions()
# 2. Given url  --> opens url using $BROWSER
# 3. Given web query --> opens using web() similar to ddg !syntax
# Default --> Runs command ala exec
declare -A web 
declare -A extensions
web=(
["@g"]="https://encrypted.google.com/search?hl=en&q="
["@w"]="https://en.wikipedia.org/w/index.php?search="
["@ddg"]="https://duckduckgo.com/?q="
["@yt"]="https://www.youtube.com/results?search_query="
["@aw"]="https://wiki.archlinux.org/index.php?search="
["@so"]="http://stackoverflow.com/search?q="
["@gh"]="http://github.com/search?q="
["@wa"]="http://wolframalpha.com/input?i="
)
extensions=(
["jpg"]="feh"
["png"]="feh"
["gif"]="feh"
["pdf"]="zathura"
["doc"]="abiword"
["docx"]="abiword"
["md"]="urxvt -e vim"
["html"]="$BROWSER"
["htm"]="$BROWSER"
["xcf"]="gimp"
)


#Only 1 ARG, check url or extension
if [ ${#@} == 1 ]; then
	#Just a single File
	if [[ -f $@ ]]; then
		export extension=`echo $@ | awk 'match($0,/^.+\.(.+)$/,a){print a[1]}'`
		if [[ -n "${extensions[$extension]}" ]]; then
			eval "${extensions[$extension]} $@"
		fi
	else
		export isUrl=`url $@`
		if [[ "$isUrl" == "1" ]]; then
			#Passed a URL
			eval "$BROWSER $@" && touch /tmp/refresh-bar
			exit
		fi
	fi
fi

#Multiple Args, check if is web query or just a command
for arg in $@; do
	if   [ -n "${web["$arg"]}" ]; then
		#Web Query -- Pop browser at the front with request string
		queryString=${web["$arg"]}
	else
		#Just another generic arg
		exec="$exec$arg "&& touch /tmp/refresh-bar
	fi
done

if   [ -n "$queryString" ]; then
	eval $BROWSER "'$queryString'" 
  exec touch /tmp/refresh-bar
else
	eval $exec && touch /tmp/refresh-bar
fi

