#!/usr/bin/env ruby
# A simple quick and dirty dmenu file browser
# Takes in one param of directory to begin in
# then you can browse till you hit a file, then 
# passes whatever file you hit to $handler.
# Entering directories respawns dmenu
# Also ../ may be entered to go to the previous directory


#Options
$dmenuOptions = { 
  # Assumes dmenu with q,xywh,xft patches
  # http://github.com/mil/dmenu-q-xywh-xft
  :h => 40,
  :x => 5,
  :y => 360 ,
  :w => 1014,
  :fn => 'Envy Code R-13',
  :sb => '#0073bf',
  :sf => '#ffffff',
  :nb => '#000000',
  :nf => '#c4c4c4'
}


def dmenuOptsToString(optsHash, pwd)
  returnString = "dmenu -p '#{pwd}'"
  optsHash.each do |option, value|
    if (value.is_a? String)
      value = "'#{value}'"
    end
    returnString = "#{returnString} -#{option} #{value}"
  end

  return returnString
end
  dm = dmenuOptsToString($dmenuOptions, "surf")
  puts %x[#{dm}]
