#!/usr/bin/env ruby
# A dmenu display customization script
# Assumes dmenu with q,xywh,xft patches
# http://github.com/mil/dmenu-q-xywh-xft

# Setup Screen Dimensions Info
xr = %x[xrandr | head -n1 | cut -d, -f2 | cut -d " " -f3-5].split(" x ")
$screen = {
  :width => xr[0].to_i,
  :height => xr[1].to_i
}

# Setup App Dimensions Info
$app = {}

# Defaults
$defaults = { 
  :h => 40,
  :x => 10,
  :y => ($screen[:height] / 2) - 20,
  :w => $screen[:width] - 20,
  :fn => 'Envy Code R-13',
  :sb => '#0073bf',
  :sf => '#ffffff',
  :nb => '#000000',
  :nf => '#c4c4c4',
  :p  => 'Rd Menu'
}

#Profiles
$profiles = {
  "launch" => {
    :p => "Launch"
  },
  "foowm" => {
    :p => "Foo-WM",
    :fn => "Envy Code R-14",
    :sb => "#91ff00",
    :sf => "#000000"
  },
  "jump" => {
    :p => "Jump",
    :fn => "Envy Code R-12",
    :sb => "#ffc400",
    :nf => "#ffffff",
    :sb => "#ffc400",
    :sf => "#000000"
  },
  "netcfg" => {
    :p => "Netcfg",
    :fn => "Envy Code R-11",
    :sb => "#ffc400",
    :nf => "#ffffff",
    :nb => "#000000",
    :sf => "#000000"
  },
  "surfURI" => {
    :p => "Surf"
  },
  "surfSearch" =>  {
    :p => "Search"
  },
  "wifi" => {

  }
}

def dmenuOptsToString(optsHash)
  returnString = "dmenu "
  optsHash.each do |option, value|
    if (value.is_a? String)
      value = "'#{value}'"
    end
    returnString = "#{returnString} -#{option} #{value}"
  end

  return returnString
end

def main
  if ($profiles[ARGV[0]] != nil) then
    $defaults.merge!($profiles[ARGV[0]])
  end

  dm = dmenuOptsToString($defaults) 
  puts %x[#{dm}]
end

main
