#!/usr/bin/ruby

class String
	def color(c)
		colors = { 
			:black   => "#000000", 
			:red     => "#ff0066", 
			:green   => "#1Eff00",
			:yellow  => "#3ead00", 
			:blue    => "#0080ff", 
			:magenta => '#ba0000', 
			:cyan    => '#4ca7a8', 
			:white   => "#960b81",
			:orange  => "#ff8400",
			:pink    => "#000000"
		}
		return "^fg(#{colors[c] || c})#{self}"
	end
end


#Get Battery Info
state	= File.read("/sys/class/power_supply/BAT0/status").chomp!.to_s
now 	= File.read("/sys/class/power_supply/BAT0/energy_now").to_f
full 	= File.read("/sys/class/power_supply/BAT0/energy_full").to_f
battery = "%05.2f" % ((now / full) * 100)

batteryIcon = "^i(/usr/share/icons/stlarch_icons/batt10.xbm)"
battery = "#{batteryIcon} #{battery}"




	#irc = %x[tail -n 1 /home/mil/irc/irc.freenode.net/\#hackerschool/out]
	#irc.gsub!(%r{(^.+)\s(\d{2}:\d{2})}, "#{"\\2".color(:magenta)}")
	#irc.gsub!(%r{(\<.+\>)(.+)}, "#{'\\1'.color(:cyan)} #{"\\2".color(:red)}")
	#irc = irc[0, 120]
	#ircIcon = "^i(/usr/share/icons/stlarch_icons/messenger2.xbm)".color(:pink)
	#irc = "#{ircIcon} #{irc}"

	weatherIcon = "^i(/usr/share/icons/stlarch_icons/ac14.xbm)".color(:pink)
	weather = %x[weather 11215].color(:yellow)
	weather = "#{weatherIcon} #{weather}"

	subway = "F in 20Mins".color(:blue)
	subwayIcon = "^i(/usr/share/icons/stlarch_icons/home1.xbm)".color(:pink)
	subway = "#{subwayIcon} #{subway}"

	time = Time.now.to_s.color(:white)
	time.gsub!(/:\d{2}\s.+/, '')
	timeIcon = "^i(/usr/share/icons/stlarch_icons/clock2.xbm)".color(:pink)
	time = "#{timeIcon} #{time}"

	#ip = Socket.ip_address_list.detect{|intf| intf.ipv4_private?} 

	wifi = %x[iwconfig wlan0 | perl -n -e '/ESSID:"(.+)"/ && print $1']


	s = "#{wifi} | #{battery}% | #{time} | #{subway} |  #{weather}"

	puts s
