#!/usr/bin/env ruby
xw = %x[xwininfo -id #{ARGV[0]} | head -n2 | tail -n1]
$stderr.puts xw
if (xw == nil || xw.match(/No such window with/)) then
  puts '.'
else
  m = xw.match(/\"(.+)\"/)
  if (m == nil) then
    puts "."
  else
    puts m[1].to_s
  end
end
