#!/usr/bin/env ruby
# A simple quick and dirty dmenu file browser
# Takes in one param of directory to begin in
# then you can browse till you hit a file, then 
# passes whatever file you hit to $handler.
# Entering directories respawns dmenu
# Also ../ may be entered to go to the previous directory

#Options
$handler = 'handler'
$defaultDirectory = "/home/mil"

def browse(directory)
  d = directory.gsub("/home/mil", "~")
  dm = "mdmenu browse '#{d}'"
  selectedOption = %x[ls #{directory} | #{dm}].chomp!
  if (!selectedOption) then
    exit
  end

  begin
    Dir.chdir("#{directory}/#{selectedOption}")
    browse(Dir.getwd)
  rescue
    %x[#{$handler} #{directory}/#{selectedOption}]
  end
end

def main
  if (ARGV[0]) then
    if (ARGV[0] == "") then
      exit
    else
      browse(ARGV[0])
    end
  else
    browse($defaultDirectory)
  end
end

main
