#!/usr/bin/env ruby
# Gives prompt for domain and then password and runs
# pwdhash on given domain/password combo
#
domainList = File.open("/home/mil/.domains").read
domain = %x[echo "#{domainList}" | dmenu -b ].chomp!
password = %x[echo "\n" | dmenu -b -nb black -nf black ].chomp!
encryptedPassword = %x[pwdhash "#{domain}" "#{password}"].chomp!
%x[xdotool type #{encryptedPassword}]
