theme = "miles"

[editor]
mouse = false
bufferline = "multiple"
rulers = [80, 120]
cursorline = true
popup-border = "all"
color-modes = true
auto-pairs = false

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
auto-signature-help = false 

[keys.insert]
C-p = "signature_help"
