[[language]]
name = "ruby"
auto-format = true
formatter = { command = "rubocop", args = ["--stdin", "foo.rb", "-a", "--stderr", "--fail-level", "fatal", "--server"] }

[[language]]
name = "go"
auto-format = true
formatter = { command = "gofmt" , args = [] }

[[language]]
name = "dart"
auto-format = true
formatter = {command = "dart", args = ["format", "-l", "120"]}

[[language]]
name = "html"
auto-format = true
formatter = {command = "sh", args = ["-c", "tidy -indent --tidy-mark no || true"]}

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }
