[[language]]
name = "ruby"
auto-format = true
formatter = { command = "rubocop", args = ["--stdin", "foo.rb", "-a", "--stderr", "--fail-level", "fatal", "--server"] }

[[language]]
name = "go"
auto-format = true
formatter = { command = "gofmt" , args = [] }

[[language]]
name = "dart"
auto-format = true
formatter = {command = "dart", args = ["format", "-l", "120"]}

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args = ["--stdin-filepath", "foo.js"] }

[[language]]
name = "python"
auto-format = true
language-servers = ["pylsp"]
formatter = {  command = "black", args = [ "-", "--quiet", "--line-length=79" ] }

[language-server.pylsp.config.pylsp]
plugins.pylsp_mypy.enabled = true
plugins.pylsp_mypy.live_mode = true
